main/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from .views import (
    OrderListView, OrderDetailView, add_order, archive, change_order)


urlpatterns = [
    url(r'^$', OrderListView.as_view(), name='order-list'),
    url(r'^order/(?P<pk>[0-9]+)/$',
        OrderDetailView.as_view(), name='order-detail'),
    url(r'^add/$', add_order, name='order-add'),
    url(r'^change/(?P<pk>[0-9]+)/$', change_order, name='order-change'),
    url(r'^archive_ajax/$', archive, name='order-archive'),
]

order/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    url(r'^', include('main.urls', namespace='order')),
]

main/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.core.urlresolvers import reverse
from django.db.models import Sum, F


class Client(models.Model):
    phone_number = models.CharField('Телефон', max_length=12)
    name = models.CharField('Имя', max_length=50)
    last_name = models.CharField('Фамилия', max_length=50)
    address = models.TextField('Адрес')

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'

    def __str__(self):
        return self.last_name

    def full_name(self):
        return '%s %s' % (self.last_name, self.name)

    def get_dict_object(self):
        return {
            'name': self.name,
            'phone_number': self.phone_number,
            'last_name': self.last_name,
            'address': self.address}


class OrderQuerySet(models.QuerySet):
    def amount(self):
        return self.annotate(amount=Sum(F('items__cost')*F('items__amount')))


class Order(models.Model):
    add_date = models.DateTimeField('Дата заказа', auto_now_add=True)
    last_change_date = models.DateTimeField('Дата изменения', auto_now=True)
    client = models.ForeignKey(
        Client, related_name='orders', verbose_name='Заказчик')
    archive = models.BooleanField('В архив', default=False)

    objects = OrderQuerySet.as_manager()

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'
        ordering = ('-add_date',)

    def __str__(self):
        return str(self.id)

    def get_absolute_url(self):
        return reverse('order:order-detail', args=(self.pk,))


class Item(models.Model):
    name = models.CharField('Товар', max_length=255)
    cost = models.FloatField('Цена', max_length=255)
    amount = models.FloatField('Количество', max_length=255)
    order = models.ForeignKey(
        Order, related_name='items', verbose_name='Заказ')

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        return reverse('order:item-detail', args=(self.pk,))

main/forms.py
# -*- coding: utf-8 -*-
import re

from django.forms import ModelForm
from django.forms import CharField

from .models import Client, Item


class PhoneField(CharField):
    def to_python(self, value):
        value = super().to_python(value)
        value = re.sub(r'[^\w\s]+|[\s]', r'', value)
        return value


class ClientForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name == 'phone_number':
                field.widget.attrs['class'] = \
                    'form-control input-medium bfh-phone'
                field.widget.attrs['data-format'] = '+7 (ddd) dd-dd-ddd'
            else:
                field.widget.attrs['class'] = 'form-control'

    phone_number = PhoneField(label='Телефон')

    class Meta:
        model = Client
        fields = ['phone_number', 'last_name', 'name', 'address']


class ItemForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if 'amount' in field_name:
                field.widget.attrs['class'] = 'form-control quantity'
            elif 'cost' in field_name:
                field.widget.attrs['class'] = 'form-control cost'
            else:
                field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Item
        fields = ['name', 'amount', 'cost']

    class Media:
        js = ('js/sum_order.js', 'js/change_fields_order.js')

main/views.py
# -*- coding: utf-8 -*-

from django.views.generic import ListView, DetailView
from django.shortcuts import render
from django.http import JsonResponse
from django.http import HttpResponseBadRequest
from django.forms.models import modelformset_factory
from django.core import serializers

from .models import Order, Item
from .forms import ClientForm, ItemForm
from .utils import get_dict_errors_formset


class JSONResponseMixin(object):
    """
    A mixin that can be used to render a JSON response.
    """
    def render_to_json_response(self, context, **response_kwargs):
        """
        Returns a JSON response, transforming 'context' to make the payload.
        """
        return JsonResponse(self.get_data(), safe=False)

    def get_data(self):
        """
        Returns an object that will be serialized as JSON by json.dumps().
        """
        context = serializers.serialize("json", self.get_queryset().amount())
        return context


class HybridListView(JSONResponseMixin, ListView):
    def render_to_response(self, context):
        # Look for a 'format=json' GET argument
        if self.request.GET.get('format') == 'json':
            return self.render_to_json_response(context)
        else:
            return super().render_to_response(context)


class OrderListView(HybridListView):
    queryset = Order.objects.amount()
    template_name = 'order_list.html'


class OrderDetailView(DetailView):
    model = Order
    template_name = 'order_detail.html'


class OrderUpdateView(ListView):
    template_name = 'change_order_form.html'

    def get_queryset(self):
        pk = self.kwargs.get('pk')
        self.order = Order.objects.get(id=pk)
        return Item.objects.filter(order=self.order)


def add_order(request):
    content = {}
    Itemformset = modelformset_factory(
        Item, form=ItemForm, can_delete=True,
        max_num=1, min_num=1, validate_min=True)

    if request.method == 'POST':
        form = ClientForm(request.POST)
        formset = Itemformset(request.POST)

        if form.is_valid() and formset.is_valid():
            client = form.save()
            order = Order(client=client)
            order.save()

            instances = formset.save(commit=False)
            for item in instances:
                item.order = order
                item.save()
            for obj in formset.deleted_objects:
                obj.delete()
        else:
            return HttpResponseBadRequest(
                get_dict_errors_formset(formset, form))

    else:
        form = ClientForm()
        content['form'] = form

        formset = Itemformset(queryset=Item.objects.none())
        content['formset'] = formset

    return render(request, 'add_order_form.html', content)


def change_order(request, pk):
    content = {'pk': pk}
    order = Order.objects.get(id=int(pk))
    item = Item.objects.filter(order=order)

    Itemformset = modelformset_factory(
        Item, form=ItemForm, can_delete=True,
        max_num=1, min_num=1, validate_min=True)

    if request.method == 'POST':
        form = ClientForm(request.POST)
        formset = Itemformset(request.POST)

        if form.is_valid() and formset.is_valid():
            if form.has_changed():
                form.save()

            if formset.has_changed():
                instances = formset.save(commit=False)
                for item in instances:
                    item.order = order
                    item.save()
                for obj in formset.deleted_objects:
                    obj.delete()
        else:
            return HttpResponseBadRequest(
                get_dict_errors_formset(formset, form))
    else:
        formset = Itemformset(queryset=item)
        content['formset'] = formset

        form = ClientForm(initial=order.client.get_dict_object())
        content['form'] = form

    return render(request, 'change_order_form.html', content)


def archive(request):
    if request.method == 'GET':
        id = request.GET['id']
        if id:
            item = Order.objects.get(id=int(id))
            item.archive = True
            item.save()

            return JsonResponse({'all': 'ok'})

main/templates/add_order_form.html
{% extends "index.html" %}
{% load staticfiles %}


{% block main %}
 <h2>Добавить заказ</h2>
  <form id="ajaxform" action="{% url 'order:order-add' %}" method="post">{% csrf_token %}
     
    {{ form.non_field_errors }}
    <fieldset class="form-inline">
       <legend>Заказчик:</legend>
       <div class="form-group">
           {{ form.phone_number.errors }}
           <label for="{{ form.phone_number.id_for_label }}">Телефон</label>
           {{ form.phone_number }}
       </div>
       <div class="form-group">
           {{ form.last_name.errors }}
           <label for="{{ form.last_name.id_for_label }}">Фамилия</label>
           {{ form.last_name }}
       </div>
       <div class="form-group">
           {{ form.name.errors }}
           <label for="{{ form.name.id_for_label }}">Имя</label>
           {{ form.name }}
       </div>
       </fieldset>
      <fieldset>
       <div class="form-group">
           {{ form.address.errors }}
           <label for="{{ form.address.id_for_label }}">Адрес</label>
           {{ form.address }}
       </div>
    </fieldset>
    <fieldset class="form-inline">
        <legend>Товар на сумму:&nbsp;<spin id="sum">0</spin></legend>
            <div id="management_formset">
            {{ formset.management_form }}
            
            </div>
            {% for form in formset %}
            <div class="form-group sum">
               <div class="form-group">
                    {{ form.name.errors }}
                     <label for="{{ form.name.id_for_label }}">Товар</label>
                {{ form.name }}
                </div>
                <div class="form-group">
                    {{ form.amount.errors }}
                     <label for="{{ form.amount.id_for_label }}">Количество</label>
                {{ form.amount }}
                </div>
                <div class="form-group">
                    {{ form.cost.errors }}
                     <label for="{{ form.cost.id_for_label }}">Стоимость</label>
                     {{ form.cost }}
                </div>
                {{ form.id }}
               <div class="form-group trigger">
                   
               </div>
            </div>
         {% endfor %}
         
         <span id="trigger" class="glyphicon" style="display:none;"></span>
    </fieldset>
    <div id="loading" style="display:none;">
        <span id="load_text">loading...</span>
    </div>
    <div id="form_ajax" style="display:none;">
        <span>Form submit successfully.</span>
    </div>
    <div id="form_ajax_error" style="display:none;">
        <span>Can not submit data due to errors.</span>
    </div>
     <div class="form-group">
        <button type="submit" class="btn btn-default">Submit</button>
    </div>
    </form>
{% endblock %}
{% block footer_javascript %}
{{ formset.media }}
 <script src="{% static 'js/send_form.js' %}"></script>
 {% endblock %}

main/templates/change_order_form.html
{% extends "index.html" %}
{% load staticfiles %}

{% block main %}
 <h2>Изменить заказ</h2>
 <form id="ajaxform" action="{% url 'order:order-change' pk %}" method="post">{% csrf_token %}
     
    {{ form.non_field_errors }}
    <fieldset class="form-inline">
       <legend>Заказчик:</legend>
       <div class="form-group">
           {{ form.phone_number.errors }}
           <label for="{{ form.phone_number.id_for_label }}">Телефон</label>
           {{ form.phone_number }}
       </div>
       <div class="form-group">
           {{ form.last_name.errors }}
           <label for="{{ form.last_name.id_for_label }}">Фамилия</label>
           {{ form.last_name }}
       </div>
       <div class="form-group">
           {{ form.name.errors }}
           <label for="{{ form.name.id_for_label }}">Имя</label>
           {{ form.name }}
       </div>
       </fieldset>
      <fieldset>
       <div class="form-group">
           {{ form.address.errors }}
           <label for="{{ form.address.id_for_label }}">Адрес</label>
           {{ form.address }}
       </div>
    </fieldset>
    <fieldset class="form-inline">
        <legend>Товар на сумму:&nbsp;<spin id="sum">0</spin></legend>
            <div id="management_formset">
            {{ formset.management_form }}
            </div>
            {% for form in formset %}
            <div class="form-group sum">
               <div class="form-group">
                    {{ form.name.errors }}
                     <label for="{{ form.name.id_for_label }}">Товар</label>
                {{ form.name }}
                </div>
                <div class="form-group">
                    {{ form.amount.errors }}
                     <label for="{{ form.amount.id_for_label }}">Количество</label>
                {{ form.amount }}
                </div>
                <div class="form-group">
                    {{ form.cost.errors }}
                     <label for="{{ form.cost.id_for_label }}">Стоимость</label>
                     {{ form.cost }}
                </div>
                {{ form.id }}
               <div class="form-group trigger">
                   
               </div>
            </div>
         {% endfor %}
         <span id="trigger" class="glyphicon" style="display:none;"></span>
    </fieldset>
    <div id="loading" style="display:none;">
        <span id="load_text">loading...</span>
    </div>
    <div id="form_ajax" style="display:none;">
        <span>Form submit successfully.</span>
    </div>
    <div id="form_ajax_error" style="display:none;">
        <span>Can not submit data due to errors.</span>
    </div>
     <div class="form-group">
        <button type="submit" class="btn btn-default">Submit</button>
    </div>
    </form>
 {% endblock %}
 {% block footer_javascript %}
 {{ formset.media }}
 <script src="{% static 'js/send_form.js' %}"></script>
 {% endblock %}

main/templates/order_detail.html
{% extends "index.html" %}
{% load phone_number %}

{% block main %}
    {{ object.name }}
    
{% endblock %}

main/templates/order_list.html
{% extends "index.html" %}
{% load staticfiles %}
{% load phone_number %}

{% block main %}
 <h2>Заказы</h2>
 <div>
     <div id="search">
         <div class="row">
            <div>
             <div class="checkbox">
                <label>
                  <input id="archive_checkbox" type="checkbox">
                                              Показывать архивные заказы
                </label>
             </div>
            <div class="input-group">
                <span class="input-group-addon">Поиск по телефону</span>
                <input id="phone_search" type="text"
                       class="form-control input-medium bfh-phone"
                       data-format="+7 (ddd) dd-dd-ddd">
              
                <span class="input-group-addon">Дата заказа от</span>
                <input id="min" name="min" type="text" class="form-control">
              
                <span class="input-group-addon">Дата заказа по</span>
                <input id="max" name="max" type="text" class="form-control">
              </div><!-- /input-group -->
             </div><!-- /.col-lg-8 -->
          </div><!-- /.row -->
     </div>
     
    <table id="table_id" class="display">
        <thead>
            <tr>
                <th>Дата заказа</th>
                <th>Дата изменения заказа</th>
                <th>Телефон</th>
                <th>Заказчик</th>
                <th>Адрес заказчика</th>
                <th>Стоимость заказа</th>
                <th>Изменить</th>
                <th>В архив</th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <th>Дата заказа</th>
                <th>Дата изменения заказа</th>
                <th>Телефон</th>
                <th>Заказчик</th>
                <th>Адрес заказчика</th>
                <th>Стоимость заказа</th>
                <th>Изменить</th>
                <th>В архив</th>
            </tr>
        </tfoot>
        <tbody>
        {% for order in object_list %}
        <tr {% if order.archive %}data-archive="1"{% endif %}>
            <td>{{ order.add_date|date:"d.m.Y H:i" }}</td>
            <td>{{ order.last_change_date|date:"d.m.Y H:i" }}</td>
            <td>{{ order.client.phone_number|phone_format }}</td>
            <td>{{ order.client.full_name }}</td>
            <td>{{ order.client.address }}</td>
            <td>{{ order.amount|floatformat:2 }}</td>
            {% if not order.archive %}
                <td class="change" item="{{ order.id }}">
                  <a href="{% url 'order:order-change' order.id %}" 
                         class="btn btn-default" role="button">Изменить</a>
                </td>
                <td class="archive" item="{{ order.id }}">
                    <button class="btn btn-default">В архив</button>
                </td>
            {% else %}   
               <td></td>
               <td>Архив</td>
            {% endif %}
            
        </tr>
            {% endfor %}
          </tbody>
    </table>
</div>
<button id="get">get</button>
{% endblock %}
 {% block footer_javascript %}
    <script src="{% static 'js/archive.js' %}"></script>
    <script src="{% static 'js/initDataTables.js' %}"></script> 
 {% endblock %}

templates/base.html
{% load staticfiles %}
{% load i18n %} 
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>{% block head_title %}{% trans "Zz" %}{% endblock %}</title>
        <link rel="shortcut icon" href="{% static 'favicon.ico' %}"
                                                      type="image/x-icon">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <style>
            body {
                padding-top: 50px;
                padding-bottom: 20px;
            }
        </style>
        <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
        <link rel="stylesheet" href="{% static 'DataTables-1.10.10/media/css/jquery.dataTables.css' %}">
        <link rel="stylesheet" href="{% static 'datapicker/jquery-ui.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">

        <script src="{% static 'js/vendor/modernizr-2.8.3-respond-1.4.2.min.js' %}"></script>
        {% block head_css %}{% endblock %}
        {% block head_javascript %}{% endblock %}
    </head>
    <body>
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
  {% block navbar %}      
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'order:order-list' %}">{% trans "Zakaz" %}</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'order:order-add' %}">{% trans "Сделать заказ" %}</a></li>
          </ul>
          
        </div><!--/.navbar-collapse -->
      </div>
    </nav>
    {% endblock %}
   
    {% block content %}{% endblock %}
   
    <hr>
    <div class="container">
      <footer>
        <p>&copy; Zakaz 2015</p>
      </footer>
    </div> <!-- /container -->    
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="static/js/vendor/jquery-1.11.2.min.js"><\/script>')</script>
        <script src="{% static 'js/vendor/jquery.form.min.js' %}"></script>
        <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/vendor/bootstrap-formhelpers-phone.js' %}"></script>
        <script src="{% static 'datapicker/jquery-ui.min.js' %}"></script>
        <script type="text/javascript" charset="utf8" src="{% static 'DataTables-1.10.10/media/js/jquery.dataTables.js' %}"></script>
       
        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script>
            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='//www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','UA-XXXXX-X','auto');ga('send','pageview');
        </script>
        {% block footer_javascript %}{% endblock %}
    </body>
</html>

templates/index.html
{% extends "base.html" %}
 
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-14 col-md-10">{% block main %}{% endblock %}</div>
            <div class="col-xs-4 col-md-2">{% block side %}{% endblock %}</div>
        </div>
    </div>
{% endblock %}